CREATE TABLE IF NOT EXISTS Registration (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  age INT NOT NULL,
  eventType VARCHAR(50) NOT NULL,
  shirtSize VARCHAR(10) NOT NULL,
  deliveryMethod VARCHAR(50) NOT NULL,
  shippingAddress TEXT,
  emergencyContact VARCHAR(255) NOT NULL,
  emergencyPhone VARCHAR(20) NOT NULL,
  paymentStatus VARCHAR(20) DEFAULT 'pending',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Payment (
  id INT PRIMARY KEY AUTO_INCREMENT,
  registrationId INT UNIQUE,
  amount DECIMAL(10,2) NOT NULL,
  paymentMethod VARCHAR(50) NOT NULL,
  paymentDate TIMESTAMP NULL,
  paymentStatus VARCHAR(20) DEFAULT 'pending',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (registrationId) REFERENCES Registration(id)
);

CREATE TABLE IF NOT EXISTS AdminUser (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 